# Generated by Django 2.2.3 on 2020-04-30 03:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circular',
            options={'ordering': ['-hora'], 'verbose_name': 'Circular', 'verbose_name_plural': 'Circulares'},
        ),
        migrations.AlterField(
            model_name='circular',
            name='contenido',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
    ]
