# Generated by Django 2.2.3 on 2020-04-20 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circular',
            options={'ordering': ['creacion'], 'verbose_name': 'Circular', 'verbose_name_plural': 'Circulares'},
        ),
    ]
