# Generated by Django 2.2.3 on 2020-01-14 16:17

import core.models
import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docentes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, validators=[core.validators.validate_only_letters, django.core.validators.MinLengthValidator(7)], verbose_name='Nombre')),
                ('lema', models.CharField(max_length=50, validators=[core.validators.validate_only_letters, django.core.validators.MinLengthValidator(7)], verbose_name='Lema')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='colegio', verbose_name='Logo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('direccion', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=12, validators=[core.validators.validate_only_numbers, django.core.validators.MinLengthValidator(5)], verbose_name='Telefono')),
                ('horarios', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Horarios')),
                ('mision', models.TextField(verbose_name='Misión')),
                ('vision', models.TextField(verbose_name='Vision')),
                ('historia', models.TextField(verbose_name='Historia')),
                ('creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('edicion', models.DateField(auto_now=True, verbose_name='Fecha de edicion')),
            ],
            options={
                'verbose_name': 'Colegio',
                'verbose_name_plural': 'Colegio',
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, unique=True, validators=[core.validators.validate_only_letters, django.core.validators.MinLengthValidator(4)], verbose_name='Nombre')),
                ('jornada', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Jornadas')),
                ('numeracion', models.IntegerField(error_messages={'unique': 'Ya existe un grado con esta numeracion'}, unique=True, verbose_name='Numeracion')),
                ('imagen', models.ImageField(upload_to=core.models.custom_upload_to_grado, verbose_name='Imagen')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('edicion', models.DateField(auto_now=True, verbose_name='Fecha de edicion')),
                ('materias', models.ManyToManyField(blank=True, related_name='get_materias', to='docentes.Materia', verbose_name='Asignaturas que ve')),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
                'ordering': ['numeracion'],
            },
        ),
    ]
