# Generated by Django 2.2.3 on 2019-10-30 23:26

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('lema', models.CharField(blank=True, max_length=300, null=True, verbose_name='Lema')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='colegio', verbose_name='Logo')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('direccion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefono')),
                ('horarios', models.CharField(blank=True, max_length=500, null=True, verbose_name='Horarios')),
                ('mision', models.TextField(verbose_name='Misión')),
                ('vision', models.TextField(verbose_name='Vision')),
                ('historia', models.TextField(verbose_name='Historia')),
                ('creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('edicion', models.DateField(auto_now=True, verbose_name='Fecha de edicion')),
            ],
            options={
                'verbose_name': 'Colegio',
                'verbose_name_plural': 'Colegio',
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, verbose_name='Nombre')),
                ('jornada', models.CharField(max_length=20, verbose_name='Jornadas')),
                ('numeracion', models.IntegerField(verbose_name='Numeracion')),
                ('imagen', models.ImageField(upload_to=core.models.custom_upload_to_grado, verbose_name='Imagen')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('edicion', models.DateField(auto_now=True, verbose_name='Fecha de edicion')),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
                'ordering': ['numeracion'],
            },
        ),
    ]
