# Generated by Django 2.2.3 on 2020-04-30 03:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegio',
            name='historia',
            field=ckeditor.fields.RichTextField(verbose_name='Historia'),
        ),
    ]
