# Generated by Django 2.2.3 on 2019-11-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_grado_materias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grado',
            name='materias',
            field=models.ManyToManyField(related_name='get_materias', to='docentes.Materia', verbose_name='Asignaturas que ve'),
        ),
    ]
