# Generated by Django 2.2.3 on 2020-01-14 16:18

import core.validators
import django.core.validators
from django.db import migrations, models
import docentes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True, validators=[core.validators.validate_only_letters, django.core.validators.MinLengthValidator(4)], verbose_name='Nombre')),
                ('creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('edicion', models.DateField(auto_now=True, verbose_name='Fecha de edicion')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=12, validators=[core.validators.validate_only_letters, django.core.validators.MinLengthValidator(2)], verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=12, validators=[core.validators.validate_only_letters, django.core.validators.MinLengthValidator(2)], verbose_name='Apellido')),
                ('imagen', models.ImageField(upload_to=docentes.models.custom_upload_to, verbose_name='Foto')),
                ('informacion', models.TextField(blank=True, max_length=150, null=True, verbose_name='Información')),
                ('creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('edicion', models.DateField(auto_now=True, verbose_name='Fecha de edicion')),
                ('materias', models.ManyToManyField(related_name='obtener_docentes', to='docentes.Materia', verbose_name='Materias que enseña')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
    ]
