# Generated by Django 2.2.3 on 2019-09-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='estado',
            field=models.BooleanField(default=1, verbose_name='Activo/Inactivo'),
            preserve_default=False,
        ),
    ]
